---
k3s_version: v1.21.1+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system

# If you define multiple masters you should be providing a loadbalanced
# apiserver endpoint to all masters here. This default value is only suitable
# for a non-HA setup, if used in a HA setup, it will not protect you if the
# first node fails.
# Also you should define k3s_token so that masters can talk together securely

apiserver_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
# k3s_token: "mysupersecuretoken"

extra_server_args: ""
extra_agent_args: ""
